//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace icehockeyWA.IceIceBaby {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TempGameDetails", Namespace="http://schemas.datacontract.org/2004/07/IceWAService")]
    public partial class TempGameDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int _awayManagerIDField;
        
        private string _awayManagerNameField;
        
        private int _awayTeamIDField;
        
        private int _homeManagerIDField;
        
        private string _homeManagerNameField;
        
        private int _homeTeamIDField;
        
        private string _linesman1Field;
        
        private string _linesman2Field;
        
        private string _ringadingField;
        
        private int awayManagerIDField;
        
        private string awayManagerNameField;
        
        private int awayTeamIDField;
        
        private int homeManagerIDField;
        
        private string homeManagerNameField;
        
        private int homeTeamIDField;
        
        private string linesman1Field;
        
        private string linesman2Field;
        
        private string ringadingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _awayManagerID {
            get {
                return this._awayManagerIDField;
            }
            set {
                if ((this._awayManagerIDField.Equals(value) != true)) {
                    this._awayManagerIDField = value;
                    this.RaisePropertyChanged("_awayManagerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _awayManagerName {
            get {
                return this._awayManagerNameField;
            }
            set {
                if ((object.ReferenceEquals(this._awayManagerNameField, value) != true)) {
                    this._awayManagerNameField = value;
                    this.RaisePropertyChanged("_awayManagerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _awayTeamID {
            get {
                return this._awayTeamIDField;
            }
            set {
                if ((this._awayTeamIDField.Equals(value) != true)) {
                    this._awayTeamIDField = value;
                    this.RaisePropertyChanged("_awayTeamID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _homeManagerID {
            get {
                return this._homeManagerIDField;
            }
            set {
                if ((this._homeManagerIDField.Equals(value) != true)) {
                    this._homeManagerIDField = value;
                    this.RaisePropertyChanged("_homeManagerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _homeManagerName {
            get {
                return this._homeManagerNameField;
            }
            set {
                if ((object.ReferenceEquals(this._homeManagerNameField, value) != true)) {
                    this._homeManagerNameField = value;
                    this.RaisePropertyChanged("_homeManagerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _homeTeamID {
            get {
                return this._homeTeamIDField;
            }
            set {
                if ((this._homeTeamIDField.Equals(value) != true)) {
                    this._homeTeamIDField = value;
                    this.RaisePropertyChanged("_homeTeamID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _linesman1 {
            get {
                return this._linesman1Field;
            }
            set {
                if ((object.ReferenceEquals(this._linesman1Field, value) != true)) {
                    this._linesman1Field = value;
                    this.RaisePropertyChanged("_linesman1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _linesman2 {
            get {
                return this._linesman2Field;
            }
            set {
                if ((object.ReferenceEquals(this._linesman2Field, value) != true)) {
                    this._linesman2Field = value;
                    this.RaisePropertyChanged("_linesman2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ringading {
            get {
                return this._ringadingField;
            }
            set {
                if ((object.ReferenceEquals(this._ringadingField, value) != true)) {
                    this._ringadingField = value;
                    this.RaisePropertyChanged("_ringading");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int awayManagerID {
            get {
                return this.awayManagerIDField;
            }
            set {
                if ((this.awayManagerIDField.Equals(value) != true)) {
                    this.awayManagerIDField = value;
                    this.RaisePropertyChanged("awayManagerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string awayManagerName {
            get {
                return this.awayManagerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.awayManagerNameField, value) != true)) {
                    this.awayManagerNameField = value;
                    this.RaisePropertyChanged("awayManagerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int awayTeamID {
            get {
                return this.awayTeamIDField;
            }
            set {
                if ((this.awayTeamIDField.Equals(value) != true)) {
                    this.awayTeamIDField = value;
                    this.RaisePropertyChanged("awayTeamID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int homeManagerID {
            get {
                return this.homeManagerIDField;
            }
            set {
                if ((this.homeManagerIDField.Equals(value) != true)) {
                    this.homeManagerIDField = value;
                    this.RaisePropertyChanged("homeManagerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string homeManagerName {
            get {
                return this.homeManagerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.homeManagerNameField, value) != true)) {
                    this.homeManagerNameField = value;
                    this.RaisePropertyChanged("homeManagerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int homeTeamID {
            get {
                return this.homeTeamIDField;
            }
            set {
                if ((this.homeTeamIDField.Equals(value) != true)) {
                    this.homeTeamIDField = value;
                    this.RaisePropertyChanged("homeTeamID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string linesman1 {
            get {
                return this.linesman1Field;
            }
            set {
                if ((object.ReferenceEquals(this.linesman1Field, value) != true)) {
                    this.linesman1Field = value;
                    this.RaisePropertyChanged("linesman1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string linesman2 {
            get {
                return this.linesman2Field;
            }
            set {
                if ((object.ReferenceEquals(this.linesman2Field, value) != true)) {
                    this.linesman2Field = value;
                    this.RaisePropertyChanged("linesman2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ringading {
            get {
                return this.ringadingField;
            }
            set {
                if ((object.ReferenceEquals(this.ringadingField, value) != true)) {
                    this.ringadingField = value;
                    this.RaisePropertyChanged("ringading");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TempGame", Namespace="http://schemas.datacontract.org/2004/07/IceWAService")]
    public partial class TempGame : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _awayTeamField;
        
        private string _exceptionField;
        
        private int _gameIDField;
        
        private string _homeTeamField;
        
        private string _sField;
        
        private System.DateTime _timeField;
        
        private string _venueField;
        
        private string awayTeamField;
        
        private string exceptionField;
        
        private int gameIDField;
        
        private string homeTeamField;
        
        private bool isfuckedField;
        
        private string sField;
        
        private System.DateTime timeField;
        
        private string venueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _awayTeam {
            get {
                return this._awayTeamField;
            }
            set {
                if ((object.ReferenceEquals(this._awayTeamField, value) != true)) {
                    this._awayTeamField = value;
                    this.RaisePropertyChanged("_awayTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _exception {
            get {
                return this._exceptionField;
            }
            set {
                if ((object.ReferenceEquals(this._exceptionField, value) != true)) {
                    this._exceptionField = value;
                    this.RaisePropertyChanged("_exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _gameID {
            get {
                return this._gameIDField;
            }
            set {
                if ((this._gameIDField.Equals(value) != true)) {
                    this._gameIDField = value;
                    this.RaisePropertyChanged("_gameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _homeTeam {
            get {
                return this._homeTeamField;
            }
            set {
                if ((object.ReferenceEquals(this._homeTeamField, value) != true)) {
                    this._homeTeamField = value;
                    this.RaisePropertyChanged("_homeTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _s {
            get {
                return this._sField;
            }
            set {
                if ((object.ReferenceEquals(this._sField, value) != true)) {
                    this._sField = value;
                    this.RaisePropertyChanged("_s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _time {
            get {
                return this._timeField;
            }
            set {
                if ((this._timeField.Equals(value) != true)) {
                    this._timeField = value;
                    this.RaisePropertyChanged("_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _venue {
            get {
                return this._venueField;
            }
            set {
                if ((object.ReferenceEquals(this._venueField, value) != true)) {
                    this._venueField = value;
                    this.RaisePropertyChanged("_venue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string awayTeam {
            get {
                return this.awayTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.awayTeamField, value) != true)) {
                    this.awayTeamField = value;
                    this.RaisePropertyChanged("awayTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string exception {
            get {
                return this.exceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.exceptionField, value) != true)) {
                    this.exceptionField = value;
                    this.RaisePropertyChanged("exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gameID {
            get {
                return this.gameIDField;
            }
            set {
                if ((this.gameIDField.Equals(value) != true)) {
                    this.gameIDField = value;
                    this.RaisePropertyChanged("gameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string homeTeam {
            get {
                return this.homeTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.homeTeamField, value) != true)) {
                    this.homeTeamField = value;
                    this.RaisePropertyChanged("homeTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isfucked {
            get {
                return this.isfuckedField;
            }
            set {
                if ((this.isfuckedField.Equals(value) != true)) {
                    this.isfuckedField = value;
                    this.RaisePropertyChanged("isfucked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string s {
            get {
                return this.sField;
            }
            set {
                if ((object.ReferenceEquals(this.sField, value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                if ((this.timeField.Equals(value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string venue {
            get {
                return this.venueField;
            }
            set {
                if ((object.ReferenceEquals(this.venueField, value) != true)) {
                    this.venueField = value;
                    this.RaisePropertyChanged("venue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TempPlayer", Namespace="http://schemas.datacontract.org/2004/07/IceWAService")]
    public partial class TempPlayer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int _playerIDField;
        
        private string _playerNameField;
        
        private int _playerNumberField;
        
        private int playerIDField;
        
        private string playerNameField;
        
        private int playerNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _playerID {
            get {
                return this._playerIDField;
            }
            set {
                if ((this._playerIDField.Equals(value) != true)) {
                    this._playerIDField = value;
                    this.RaisePropertyChanged("_playerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _playerName {
            get {
                return this._playerNameField;
            }
            set {
                if ((object.ReferenceEquals(this._playerNameField, value) != true)) {
                    this._playerNameField = value;
                    this.RaisePropertyChanged("_playerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _playerNumber {
            get {
                return this._playerNumberField;
            }
            set {
                if ((this._playerNumberField.Equals(value) != true)) {
                    this._playerNumberField = value;
                    this.RaisePropertyChanged("_playerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int playerID {
            get {
                return this.playerIDField;
            }
            set {
                if ((this.playerIDField.Equals(value) != true)) {
                    this.playerIDField = value;
                    this.RaisePropertyChanged("playerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string playerName {
            get {
                return this.playerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.playerNameField, value) != true)) {
                    this.playerNameField = value;
                    this.RaisePropertyChanged("playerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int playerNumber {
            get {
                return this.playerNumberField;
            }
            set {
                if ((this.playerNumberField.Equals(value) != true)) {
                    this.playerNumberField = value;
                    this.RaisePropertyChanged("playerNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IceIceBaby.IIceWAService")]
    public interface IIceWAService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IIceWAService/returnTeams", ReplyAction="http://tempuri.org/IIceWAService/returnTeamsResponse")]
        System.IAsyncResult BeginreturnTeams(string div, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndreturnTeams(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IIceWAService/getDivisions", ReplyAction="http://tempuri.org/IIceWAService/getDivisionsResponse")]
        System.IAsyncResult BegingetDivisions(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndgetDivisions(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IIceWAService/returnGameDetails", ReplyAction="http://tempuri.org/IIceWAService/returnGameDetailsResponse")]
        System.IAsyncResult BeginreturnGameDetails(int gameID, System.AsyncCallback callback, object asyncState);
        
        icehockeyWA.IceIceBaby.TempGameDetails EndreturnGameDetails(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IIceWAService/returnSchedule", ReplyAction="http://tempuri.org/IIceWAService/returnScheduleResponse")]
        System.IAsyncResult BeginreturnSchedule(System.DateTime date, string division, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempGame> EndreturnSchedule(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IIceWAService/returnPlayers", ReplyAction="http://tempuri.org/IIceWAService/returnPlayersResponse")]
        System.IAsyncResult BeginreturnPlayers(int teamID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer> EndreturnPlayers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IIceWAService/searchPlayers", ReplyAction="http://tempuri.org/IIceWAService/searchPlayersResponse")]
        System.IAsyncResult BeginsearchPlayers(string query, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer> EndsearchPlayers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IIceWAService/addGoal", ReplyAction="http://tempuri.org/IIceWAService/addGoalResponse")]
        System.IAsyncResult BeginaddGoal(int ID, int gameID, int teamID, int playerID, int period, string time, int playass1ID, int playass2ID, System.AsyncCallback callback, object asyncState);
        
        string EndaddGoal(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IIceWAService/addPenalty", ReplyAction="http://tempuri.org/IIceWAService/addPenaltyResponse")]
        System.IAsyncResult BeginaddPenalty(int ID, int gameID, int teamID, int playerID, int period, string time, string Offence, int timeGiven, System.AsyncCallback callback, object asyncState);
        
        string EndaddPenalty(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIceWAServiceChannel : icehockeyWA.IceIceBaby.IIceWAService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class returnTeamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public returnTeamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getDivisionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getDivisionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class returnGameDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public returnGameDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public icehockeyWA.IceIceBaby.TempGameDetails Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((icehockeyWA.IceIceBaby.TempGameDetails)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class returnScheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public returnScheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempGame> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempGame>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class returnPlayersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public returnPlayersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class searchPlayersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public searchPlayersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addGoalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public addGoalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addPenaltyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public addPenaltyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IceWAServiceClient : System.ServiceModel.ClientBase<icehockeyWA.IceIceBaby.IIceWAService>, icehockeyWA.IceIceBaby.IIceWAService {
        
        private BeginOperationDelegate onBeginreturnTeamsDelegate;
        
        private EndOperationDelegate onEndreturnTeamsDelegate;
        
        private System.Threading.SendOrPostCallback onreturnTeamsCompletedDelegate;
        
        private BeginOperationDelegate onBegingetDivisionsDelegate;
        
        private EndOperationDelegate onEndgetDivisionsDelegate;
        
        private System.Threading.SendOrPostCallback ongetDivisionsCompletedDelegate;
        
        private BeginOperationDelegate onBeginreturnGameDetailsDelegate;
        
        private EndOperationDelegate onEndreturnGameDetailsDelegate;
        
        private System.Threading.SendOrPostCallback onreturnGameDetailsCompletedDelegate;
        
        private BeginOperationDelegate onBeginreturnScheduleDelegate;
        
        private EndOperationDelegate onEndreturnScheduleDelegate;
        
        private System.Threading.SendOrPostCallback onreturnScheduleCompletedDelegate;
        
        private BeginOperationDelegate onBeginreturnPlayersDelegate;
        
        private EndOperationDelegate onEndreturnPlayersDelegate;
        
        private System.Threading.SendOrPostCallback onreturnPlayersCompletedDelegate;
        
        private BeginOperationDelegate onBeginsearchPlayersDelegate;
        
        private EndOperationDelegate onEndsearchPlayersDelegate;
        
        private System.Threading.SendOrPostCallback onsearchPlayersCompletedDelegate;
        
        private BeginOperationDelegate onBeginaddGoalDelegate;
        
        private EndOperationDelegate onEndaddGoalDelegate;
        
        private System.Threading.SendOrPostCallback onaddGoalCompletedDelegate;
        
        private BeginOperationDelegate onBeginaddPenaltyDelegate;
        
        private EndOperationDelegate onEndaddPenaltyDelegate;
        
        private System.Threading.SendOrPostCallback onaddPenaltyCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public IceWAServiceClient() {
        }
        
        public IceWAServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IceWAServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IceWAServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IceWAServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<returnTeamsCompletedEventArgs> returnTeamsCompleted;
        
        public event System.EventHandler<getDivisionsCompletedEventArgs> getDivisionsCompleted;
        
        public event System.EventHandler<returnGameDetailsCompletedEventArgs> returnGameDetailsCompleted;
        
        public event System.EventHandler<returnScheduleCompletedEventArgs> returnScheduleCompleted;
        
        public event System.EventHandler<returnPlayersCompletedEventArgs> returnPlayersCompleted;
        
        public event System.EventHandler<searchPlayersCompletedEventArgs> searchPlayersCompleted;
        
        public event System.EventHandler<addGoalCompletedEventArgs> addGoalCompleted;
        
        public event System.EventHandler<addPenaltyCompletedEventArgs> addPenaltyCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult icehockeyWA.IceIceBaby.IIceWAService.BeginreturnTeams(string div, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginreturnTeams(div, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> icehockeyWA.IceIceBaby.IIceWAService.EndreturnTeams(System.IAsyncResult result) {
            return base.Channel.EndreturnTeams(result);
        }
        
        private System.IAsyncResult OnBeginreturnTeams(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string div = ((string)(inValues[0]));
            return ((icehockeyWA.IceIceBaby.IIceWAService)(this)).BeginreturnTeams(div, callback, asyncState);
        }
        
        private object[] OnEndreturnTeams(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((icehockeyWA.IceIceBaby.IIceWAService)(this)).EndreturnTeams(result);
            return new object[] {
                    retVal};
        }
        
        private void OnreturnTeamsCompleted(object state) {
            if ((this.returnTeamsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.returnTeamsCompleted(this, new returnTeamsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void returnTeamsAsync(string div) {
            this.returnTeamsAsync(div, null);
        }
        
        public void returnTeamsAsync(string div, object userState) {
            if ((this.onBeginreturnTeamsDelegate == null)) {
                this.onBeginreturnTeamsDelegate = new BeginOperationDelegate(this.OnBeginreturnTeams);
            }
            if ((this.onEndreturnTeamsDelegate == null)) {
                this.onEndreturnTeamsDelegate = new EndOperationDelegate(this.OnEndreturnTeams);
            }
            if ((this.onreturnTeamsCompletedDelegate == null)) {
                this.onreturnTeamsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnreturnTeamsCompleted);
            }
            base.InvokeAsync(this.onBeginreturnTeamsDelegate, new object[] {
                        div}, this.onEndreturnTeamsDelegate, this.onreturnTeamsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult icehockeyWA.IceIceBaby.IIceWAService.BegingetDivisions(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetDivisions(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> icehockeyWA.IceIceBaby.IIceWAService.EndgetDivisions(System.IAsyncResult result) {
            return base.Channel.EndgetDivisions(result);
        }
        
        private System.IAsyncResult OnBegingetDivisions(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((icehockeyWA.IceIceBaby.IIceWAService)(this)).BegingetDivisions(callback, asyncState);
        }
        
        private object[] OnEndgetDivisions(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((icehockeyWA.IceIceBaby.IIceWAService)(this)).EndgetDivisions(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetDivisionsCompleted(object state) {
            if ((this.getDivisionsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getDivisionsCompleted(this, new getDivisionsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getDivisionsAsync() {
            this.getDivisionsAsync(null);
        }
        
        public void getDivisionsAsync(object userState) {
            if ((this.onBegingetDivisionsDelegate == null)) {
                this.onBegingetDivisionsDelegate = new BeginOperationDelegate(this.OnBegingetDivisions);
            }
            if ((this.onEndgetDivisionsDelegate == null)) {
                this.onEndgetDivisionsDelegate = new EndOperationDelegate(this.OnEndgetDivisions);
            }
            if ((this.ongetDivisionsCompletedDelegate == null)) {
                this.ongetDivisionsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetDivisionsCompleted);
            }
            base.InvokeAsync(this.onBegingetDivisionsDelegate, null, this.onEndgetDivisionsDelegate, this.ongetDivisionsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult icehockeyWA.IceIceBaby.IIceWAService.BeginreturnGameDetails(int gameID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginreturnGameDetails(gameID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        icehockeyWA.IceIceBaby.TempGameDetails icehockeyWA.IceIceBaby.IIceWAService.EndreturnGameDetails(System.IAsyncResult result) {
            return base.Channel.EndreturnGameDetails(result);
        }
        
        private System.IAsyncResult OnBeginreturnGameDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int gameID = ((int)(inValues[0]));
            return ((icehockeyWA.IceIceBaby.IIceWAService)(this)).BeginreturnGameDetails(gameID, callback, asyncState);
        }
        
        private object[] OnEndreturnGameDetails(System.IAsyncResult result) {
            icehockeyWA.IceIceBaby.TempGameDetails retVal = ((icehockeyWA.IceIceBaby.IIceWAService)(this)).EndreturnGameDetails(result);
            return new object[] {
                    retVal};
        }
        
        private void OnreturnGameDetailsCompleted(object state) {
            if ((this.returnGameDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.returnGameDetailsCompleted(this, new returnGameDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void returnGameDetailsAsync(int gameID) {
            this.returnGameDetailsAsync(gameID, null);
        }
        
        public void returnGameDetailsAsync(int gameID, object userState) {
            if ((this.onBeginreturnGameDetailsDelegate == null)) {
                this.onBeginreturnGameDetailsDelegate = new BeginOperationDelegate(this.OnBeginreturnGameDetails);
            }
            if ((this.onEndreturnGameDetailsDelegate == null)) {
                this.onEndreturnGameDetailsDelegate = new EndOperationDelegate(this.OnEndreturnGameDetails);
            }
            if ((this.onreturnGameDetailsCompletedDelegate == null)) {
                this.onreturnGameDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnreturnGameDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginreturnGameDetailsDelegate, new object[] {
                        gameID}, this.onEndreturnGameDetailsDelegate, this.onreturnGameDetailsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult icehockeyWA.IceIceBaby.IIceWAService.BeginreturnSchedule(System.DateTime date, string division, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginreturnSchedule(date, division, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempGame> icehockeyWA.IceIceBaby.IIceWAService.EndreturnSchedule(System.IAsyncResult result) {
            return base.Channel.EndreturnSchedule(result);
        }
        
        private System.IAsyncResult OnBeginreturnSchedule(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.DateTime date = ((System.DateTime)(inValues[0]));
            string division = ((string)(inValues[1]));
            return ((icehockeyWA.IceIceBaby.IIceWAService)(this)).BeginreturnSchedule(date, division, callback, asyncState);
        }
        
        private object[] OnEndreturnSchedule(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempGame> retVal = ((icehockeyWA.IceIceBaby.IIceWAService)(this)).EndreturnSchedule(result);
            return new object[] {
                    retVal};
        }
        
        private void OnreturnScheduleCompleted(object state) {
            if ((this.returnScheduleCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.returnScheduleCompleted(this, new returnScheduleCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void returnScheduleAsync(System.DateTime date, string division) {
            this.returnScheduleAsync(date, division, null);
        }
        
        public void returnScheduleAsync(System.DateTime date, string division, object userState) {
            if ((this.onBeginreturnScheduleDelegate == null)) {
                this.onBeginreturnScheduleDelegate = new BeginOperationDelegate(this.OnBeginreturnSchedule);
            }
            if ((this.onEndreturnScheduleDelegate == null)) {
                this.onEndreturnScheduleDelegate = new EndOperationDelegate(this.OnEndreturnSchedule);
            }
            if ((this.onreturnScheduleCompletedDelegate == null)) {
                this.onreturnScheduleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnreturnScheduleCompleted);
            }
            base.InvokeAsync(this.onBeginreturnScheduleDelegate, new object[] {
                        date,
                        division}, this.onEndreturnScheduleDelegate, this.onreturnScheduleCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult icehockeyWA.IceIceBaby.IIceWAService.BeginreturnPlayers(int teamID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginreturnPlayers(teamID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer> icehockeyWA.IceIceBaby.IIceWAService.EndreturnPlayers(System.IAsyncResult result) {
            return base.Channel.EndreturnPlayers(result);
        }
        
        private System.IAsyncResult OnBeginreturnPlayers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int teamID = ((int)(inValues[0]));
            return ((icehockeyWA.IceIceBaby.IIceWAService)(this)).BeginreturnPlayers(teamID, callback, asyncState);
        }
        
        private object[] OnEndreturnPlayers(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer> retVal = ((icehockeyWA.IceIceBaby.IIceWAService)(this)).EndreturnPlayers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnreturnPlayersCompleted(object state) {
            if ((this.returnPlayersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.returnPlayersCompleted(this, new returnPlayersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void returnPlayersAsync(int teamID) {
            this.returnPlayersAsync(teamID, null);
        }
        
        public void returnPlayersAsync(int teamID, object userState) {
            if ((this.onBeginreturnPlayersDelegate == null)) {
                this.onBeginreturnPlayersDelegate = new BeginOperationDelegate(this.OnBeginreturnPlayers);
            }
            if ((this.onEndreturnPlayersDelegate == null)) {
                this.onEndreturnPlayersDelegate = new EndOperationDelegate(this.OnEndreturnPlayers);
            }
            if ((this.onreturnPlayersCompletedDelegate == null)) {
                this.onreturnPlayersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnreturnPlayersCompleted);
            }
            base.InvokeAsync(this.onBeginreturnPlayersDelegate, new object[] {
                        teamID}, this.onEndreturnPlayersDelegate, this.onreturnPlayersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult icehockeyWA.IceIceBaby.IIceWAService.BeginsearchPlayers(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsearchPlayers(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer> icehockeyWA.IceIceBaby.IIceWAService.EndsearchPlayers(System.IAsyncResult result) {
            return base.Channel.EndsearchPlayers(result);
        }
        
        private System.IAsyncResult OnBeginsearchPlayers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return ((icehockeyWA.IceIceBaby.IIceWAService)(this)).BeginsearchPlayers(query, callback, asyncState);
        }
        
        private object[] OnEndsearchPlayers(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer> retVal = ((icehockeyWA.IceIceBaby.IIceWAService)(this)).EndsearchPlayers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsearchPlayersCompleted(object state) {
            if ((this.searchPlayersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.searchPlayersCompleted(this, new searchPlayersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void searchPlayersAsync(string query) {
            this.searchPlayersAsync(query, null);
        }
        
        public void searchPlayersAsync(string query, object userState) {
            if ((this.onBeginsearchPlayersDelegate == null)) {
                this.onBeginsearchPlayersDelegate = new BeginOperationDelegate(this.OnBeginsearchPlayers);
            }
            if ((this.onEndsearchPlayersDelegate == null)) {
                this.onEndsearchPlayersDelegate = new EndOperationDelegate(this.OnEndsearchPlayers);
            }
            if ((this.onsearchPlayersCompletedDelegate == null)) {
                this.onsearchPlayersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsearchPlayersCompleted);
            }
            base.InvokeAsync(this.onBeginsearchPlayersDelegate, new object[] {
                        query}, this.onEndsearchPlayersDelegate, this.onsearchPlayersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult icehockeyWA.IceIceBaby.IIceWAService.BeginaddGoal(int ID, int gameID, int teamID, int playerID, int period, string time, int playass1ID, int playass2ID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddGoal(ID, gameID, teamID, playerID, period, time, playass1ID, playass2ID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string icehockeyWA.IceIceBaby.IIceWAService.EndaddGoal(System.IAsyncResult result) {
            return base.Channel.EndaddGoal(result);
        }
        
        private System.IAsyncResult OnBeginaddGoal(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int ID = ((int)(inValues[0]));
            int gameID = ((int)(inValues[1]));
            int teamID = ((int)(inValues[2]));
            int playerID = ((int)(inValues[3]));
            int period = ((int)(inValues[4]));
            string time = ((string)(inValues[5]));
            int playass1ID = ((int)(inValues[6]));
            int playass2ID = ((int)(inValues[7]));
            return ((icehockeyWA.IceIceBaby.IIceWAService)(this)).BeginaddGoal(ID, gameID, teamID, playerID, period, time, playass1ID, playass2ID, callback, asyncState);
        }
        
        private object[] OnEndaddGoal(System.IAsyncResult result) {
            string retVal = ((icehockeyWA.IceIceBaby.IIceWAService)(this)).EndaddGoal(result);
            return new object[] {
                    retVal};
        }
        
        private void OnaddGoalCompleted(object state) {
            if ((this.addGoalCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addGoalCompleted(this, new addGoalCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addGoalAsync(int ID, int gameID, int teamID, int playerID, int period, string time, int playass1ID, int playass2ID) {
            this.addGoalAsync(ID, gameID, teamID, playerID, period, time, playass1ID, playass2ID, null);
        }
        
        public void addGoalAsync(int ID, int gameID, int teamID, int playerID, int period, string time, int playass1ID, int playass2ID, object userState) {
            if ((this.onBeginaddGoalDelegate == null)) {
                this.onBeginaddGoalDelegate = new BeginOperationDelegate(this.OnBeginaddGoal);
            }
            if ((this.onEndaddGoalDelegate == null)) {
                this.onEndaddGoalDelegate = new EndOperationDelegate(this.OnEndaddGoal);
            }
            if ((this.onaddGoalCompletedDelegate == null)) {
                this.onaddGoalCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddGoalCompleted);
            }
            base.InvokeAsync(this.onBeginaddGoalDelegate, new object[] {
                        ID,
                        gameID,
                        teamID,
                        playerID,
                        period,
                        time,
                        playass1ID,
                        playass2ID}, this.onEndaddGoalDelegate, this.onaddGoalCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult icehockeyWA.IceIceBaby.IIceWAService.BeginaddPenalty(int ID, int gameID, int teamID, int playerID, int period, string time, string Offence, int timeGiven, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddPenalty(ID, gameID, teamID, playerID, period, time, Offence, timeGiven, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string icehockeyWA.IceIceBaby.IIceWAService.EndaddPenalty(System.IAsyncResult result) {
            return base.Channel.EndaddPenalty(result);
        }
        
        private System.IAsyncResult OnBeginaddPenalty(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int ID = ((int)(inValues[0]));
            int gameID = ((int)(inValues[1]));
            int teamID = ((int)(inValues[2]));
            int playerID = ((int)(inValues[3]));
            int period = ((int)(inValues[4]));
            string time = ((string)(inValues[5]));
            string Offence = ((string)(inValues[6]));
            int timeGiven = ((int)(inValues[7]));
            return ((icehockeyWA.IceIceBaby.IIceWAService)(this)).BeginaddPenalty(ID, gameID, teamID, playerID, period, time, Offence, timeGiven, callback, asyncState);
        }
        
        private object[] OnEndaddPenalty(System.IAsyncResult result) {
            string retVal = ((icehockeyWA.IceIceBaby.IIceWAService)(this)).EndaddPenalty(result);
            return new object[] {
                    retVal};
        }
        
        private void OnaddPenaltyCompleted(object state) {
            if ((this.addPenaltyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addPenaltyCompleted(this, new addPenaltyCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addPenaltyAsync(int ID, int gameID, int teamID, int playerID, int period, string time, string Offence, int timeGiven) {
            this.addPenaltyAsync(ID, gameID, teamID, playerID, period, time, Offence, timeGiven, null);
        }
        
        public void addPenaltyAsync(int ID, int gameID, int teamID, int playerID, int period, string time, string Offence, int timeGiven, object userState) {
            if ((this.onBeginaddPenaltyDelegate == null)) {
                this.onBeginaddPenaltyDelegate = new BeginOperationDelegate(this.OnBeginaddPenalty);
            }
            if ((this.onEndaddPenaltyDelegate == null)) {
                this.onEndaddPenaltyDelegate = new EndOperationDelegate(this.OnEndaddPenalty);
            }
            if ((this.onaddPenaltyCompletedDelegate == null)) {
                this.onaddPenaltyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddPenaltyCompleted);
            }
            base.InvokeAsync(this.onBeginaddPenaltyDelegate, new object[] {
                        ID,
                        gameID,
                        teamID,
                        playerID,
                        period,
                        time,
                        Offence,
                        timeGiven}, this.onEndaddPenaltyDelegate, this.onaddPenaltyCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override icehockeyWA.IceIceBaby.IIceWAService CreateChannel() {
            return new IceWAServiceClientChannel(this);
        }
        
        private class IceWAServiceClientChannel : ChannelBase<icehockeyWA.IceIceBaby.IIceWAService>, icehockeyWA.IceIceBaby.IIceWAService {
            
            public IceWAServiceClientChannel(System.ServiceModel.ClientBase<icehockeyWA.IceIceBaby.IIceWAService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginreturnTeams(string div, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = div;
                System.IAsyncResult _result = base.BeginInvoke("returnTeams", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndreturnTeams(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("returnTeams", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetDivisions(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getDivisions", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndgetDivisions(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("getDivisions", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginreturnGameDetails(int gameID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = gameID;
                System.IAsyncResult _result = base.BeginInvoke("returnGameDetails", _args, callback, asyncState);
                return _result;
            }
            
            public icehockeyWA.IceIceBaby.TempGameDetails EndreturnGameDetails(System.IAsyncResult result) {
                object[] _args = new object[0];
                icehockeyWA.IceIceBaby.TempGameDetails _result = ((icehockeyWA.IceIceBaby.TempGameDetails)(base.EndInvoke("returnGameDetails", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginreturnSchedule(System.DateTime date, string division, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = date;
                _args[1] = division;
                System.IAsyncResult _result = base.BeginInvoke("returnSchedule", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempGame> EndreturnSchedule(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempGame> _result = ((System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempGame>)(base.EndInvoke("returnSchedule", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginreturnPlayers(int teamID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = teamID;
                System.IAsyncResult _result = base.BeginInvoke("returnPlayers", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer> EndreturnPlayers(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer> _result = ((System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer>)(base.EndInvoke("returnPlayers", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginsearchPlayers(string query, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = query;
                System.IAsyncResult _result = base.BeginInvoke("searchPlayers", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer> EndsearchPlayers(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer> _result = ((System.Collections.ObjectModel.ObservableCollection<icehockeyWA.IceIceBaby.TempPlayer>)(base.EndInvoke("searchPlayers", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginaddGoal(int ID, int gameID, int teamID, int playerID, int period, string time, int playass1ID, int playass2ID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[8];
                _args[0] = ID;
                _args[1] = gameID;
                _args[2] = teamID;
                _args[3] = playerID;
                _args[4] = period;
                _args[5] = time;
                _args[6] = playass1ID;
                _args[7] = playass2ID;
                System.IAsyncResult _result = base.BeginInvoke("addGoal", _args, callback, asyncState);
                return _result;
            }
            
            public string EndaddGoal(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("addGoal", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginaddPenalty(int ID, int gameID, int teamID, int playerID, int period, string time, string Offence, int timeGiven, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[8];
                _args[0] = ID;
                _args[1] = gameID;
                _args[2] = teamID;
                _args[3] = playerID;
                _args[4] = period;
                _args[5] = time;
                _args[6] = Offence;
                _args[7] = timeGiven;
                System.IAsyncResult _result = base.BeginInvoke("addPenalty", _args, callback, asyncState);
                return _result;
            }
            
            public string EndaddPenalty(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("addPenalty", _args, result)));
                return _result;
            }
        }
    }
}
